// Dummy account / plan data

export const DUMMY_ACCOUNTS = [
  {
    id: 1,
    slug: 'demo-company-abc',
    name: 'Demo Company ABC',
    owner: 'Cameron Abernethy',
    phone: 'N/A',
    employees: 750,
    recordkeeper: '',
    recordkeeperWebsite: '',
    planName: '',
    planNumber: '',
    educationWebsite: '',
    financialWellnessWebsite: '',
    estatePlanningWebsite: '',
    maxPlanMatch: '',
    matchDescription: '',
    deferralEligibilityReqs: '',
    deferralEntryDates: '',
    videoLink: '',
    description: '',
    serviceContactEmail: '',
    serviceContactFirstName: '',
    serviceContactLastName: '',
    serviceContactPhone: '',
    serviceContactTitle: '',
    parentAccount: '',
    billingAddress: '',
    shippingAddress: '',
    dataLastUpdated: 'N/A',
    createdBy: 'Cameron Abernethy',
    lastModifiedBy: 'Cameron Abernethy',
    updatedAt: '2026-03-17T11:24:00',
    createdAt: '2026-03-10T09:00:00',
  },
  {
    id: 2,
    slug: 'plansync',
    name: 'PlanSync',
    owner: 'Cameron Abernethy',
    phone: '(555) 987-6543',
    employees: 1,
    recordkeeper: 'Fidelity Investments',
    recordkeeperWebsite: 'https://fidelity.com',
    planName: 'PlanSync 401(k) Plan',
    planNumber: '99001',
    educationWebsite: 'https://education.plansync.com',
    financialWellnessWebsite: 'https://wellness.plansync.com',
    estatePlanningWebsite: '',
    maxPlanMatch: '4%',
    matchDescription: '100% match on the first 3% and 50% on the next 2%',
    deferralEligibilityReqs: '90 days of service',
    deferralEntryDates: '1st of each month',
    videoLink: '',
    description: 'Internal test account for PlanSync platform development.',
    serviceContactEmail: 'cameron@plansync.com',
    serviceContactFirstName: 'Cameron',
    serviceContactLastName: 'Abernethy',
    serviceContactPhone: '(555) 987-6543',
    serviceContactTitle: 'Plan Advisor',
    parentAccount: '',
    billingAddress: '123 Innovation Dr, San Francisco, CA 94105',
    shippingAddress: '123 Innovation Dr, San Francisco, CA 94105',
    dataLastUpdated: 'Mar 17, 2026',
    createdBy: 'Cameron Abernethy',
    lastModifiedBy: 'Cameron Abernethy',
    updatedAt: '2026-03-17T11:15:00',
    createdAt: '2026-03-05T14:30:00',
  },
]

export const AUTO_TRIGGERS = [
  { key: 'termination', label: 'Termination', description: 'Send communication when a participant is terminated.' },
  { key: 'new_hire', label: 'New Hire', description: 'Send communication to newly hired participants.' },
  { key: 'birthday', label: 'Birthday', description: 'Send birthday greetings to participants.' },
  { key: '59_5', label: '59.5', description: 'Notify participants reaching age 59½ about distribution options.' },
  { key: 'rehire', label: 'Rehire', description: 'Welcome back rehired participants.' },
  { key: 'age_50_catchup', label: 'Age 50 Catch-Up', description: 'Notify participants about catch-up contribution eligibility.' },
  { key: 'ten_years_out', label: 'Ten Years Out from Retirement', description: 'Begin retirement planning conversations.' },
  { key: 'five_years_out', label: 'Five Years Out from Retirement', description: 'Accelerate retirement planning conversations.' },
  { key: 'three_years_out', label: 'Three Years Out from Retirement', description: 'Detailed retirement planning guidance.' },
  { key: 'one_year_out', label: 'One Year Out from Retirement', description: 'Final year retirement checklist.' },
  { key: 'medicare_message', label: 'Medicare Message (64 ½)', description: 'Medicare enrollment guidance.' },
  { key: 'retirement_age', label: 'Retirement Age', description: 'Communication at retirement age (65).' },
  { key: 'work_anniversary', label: 'Work Anniversary', description: 'Celebrate work anniversaries.' },
]

// Default trigger settings for accounts
export const DEFAULT_TRIGGER_SETTINGS = {
  new_hire: {
    enabled: true,
    templateId: null,
    salaryThreshold: 100000,
    deliveryTime: '11:00 AM',
    deliveryDelay: 0,
  },
}

export function getAccountStats(accounts) {
  return {
    total: accounts.length,
    withPhone: accounts.filter((a) => a.phone && a.phone !== 'N/A').length,
    withRecordkeeper: accounts.filter((a) => a.recordkeeper).length,
  }
}
