// Communication history dummy data
// Links to: contacts (by contactId matching CSV index), segments (by segmentId), and company-wide

// ─── Email templates / campaigns that were sent ────────────────────────────────
export const EMAIL_TEMPLATES = [
  { id: 'tpl-1', name: 'Q1 Benefits Enrollment Reminder', subject: 'Open Enrollment Closes Friday — Act Now' },
  { id: 'tpl-2', name: 'Welcome to Your Plan', subject: 'Welcome! Here\'s Everything You Need to Know About Your Retirement Plan' },
  { id: 'tpl-3', name: '401(k) Contribution Increase Nudge', subject: 'A Small Increase Today Could Mean $50K+ More at Retirement' },
  { id: 'tpl-4', name: 'Missing Beneficiary Alert', subject: 'Action Required: Your Beneficiary Designation Is Incomplete' },
  { id: 'tpl-5', name: 'Annual Plan Performance Summary', subject: 'Your 2025 Retirement Plan Year in Review' },
  { id: 'tpl-6', name: 'Catch-Up Contribution Eligibility', subject: 'You\'re Now Eligible for Catch-Up Contributions' },
  { id: 'tpl-7', name: 'Payroll Integration Confirmation', subject: 'Your Payroll Data Has Been Successfully Linked' },
  { id: 'tpl-8', name: 'New Hire Onboarding - Plan Intro', subject: 'Welcome Aboard! Let\'s Get You Started With Your Benefits' },
  { id: 'tpl-9', name: 'Inactive Participant Re-engagement', subject: 'We Haven\'t Heard From You — Your Plan Balance Is Waiting' },
  { id: 'tpl-10', name: 'High Balance Quarterly Check-In', subject: 'Your Quarterly Plan Balance Update & Optimization Tips' },
]

// ─── Communication event types ─────────────────────────────────────────────────
export const COMM_TYPES = {
  EMAIL_SENT: 'Email Sent',
  EMAIL_DELIVERED: 'Email Delivered',
  EMAIL_OPENED: 'Email Opened',
  EMAIL_CLICKED: 'Email Clicked',
  EMAIL_BOUNCED: 'Email Bounced',
  EMAIL_UNSUBSCRIBED: 'Unsubscribed',
  TRIGGER_FIRED: 'Trigger Fired',
  SMS_SENT: 'SMS Sent',
  CAMPAIGN_ENROLLED: 'Campaign Enrolled',
}

// Status badge styling helper
export const COMM_STATUS_STYLES = {
  'Email Sent': 'bg-blue-50 text-blue-700',
  'Email Delivered': 'bg-emerald-50 text-emerald-700',
  'Email Opened': 'bg-purple-50 text-purple-700',
  'Email Clicked': 'bg-indigo-50 text-indigo-700',
  'Email Replied': 'bg-teal-50 text-teal-700',
  'Email Bounced': 'bg-red-50 text-red-700',
  'Unsubscribed': 'bg-slate-100 text-slate-600',
  'Trigger Fired': 'bg-amber-50 text-amber-700',
  'SMS Sent': 'bg-teal-50 text-teal-700',
  'Campaign Enrolled': 'bg-primary-50 text-primary-700',
}

// ─── Main communication history records ────────────────────────────────────────
// contactId maps to the index in the parsed contacts array (from useContacts)
// contactEmail is a fallback key for matching
// segmentId maps to DUMMY_SEGMENTATIONS[].id (null = sent individually)
// campaignName groups related sends

export const COMMUNICATION_HISTORY = [
  // ── Q1 Benefits Enrollment campaign (segment 1: Test — salary > 100k) ──────
  {
    id: 'comm-001',
    contactId: 0,
    contactName: 'Abigail A. Anderson',
    contactEmail: 'abigail.anderson87@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-1',
    templateName: 'Q1 Benefits Enrollment Reminder',
    subject: 'Open Enrollment Closes Friday — Act Now',
    segmentId: 1,
    segmentName: 'Test',
    campaignName: 'Q1 Benefits Enrollment',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-23T14:30:00Z',
    deliveredAt: '2026-03-23T14:30:12Z',
    openedAt: '2026-03-23T16:45:00Z',
    clickedAt: '2026-03-23T16:46:30Z',
    repliedAt: '2026-03-23T17:15:00Z',
    status: 'Replied',
  },
  {
    id: 'comm-002',
    contactId: 1,
    contactName: 'Abigail A. Clark',
    contactEmail: 'abigail.clark213@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-1',
    templateName: 'Q1 Benefits Enrollment Reminder',
    subject: 'Open Enrollment Closes Friday — Act Now',
    segmentId: 1,
    segmentName: 'Test',
    campaignName: 'Q1 Benefits Enrollment',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-23T14:30:00Z',
    deliveredAt: '2026-03-23T14:30:08Z',
    openedAt: '2026-03-23T19:12:00Z',
    clickedAt: null,
    status: 'Opened',
  },
  {
    id: 'comm-003',
    contactId: 5,
    contactName: 'Abigail A. Thompson',
    contactEmail: 'abigail.thompson234@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-1',
    templateName: 'Q1 Benefits Enrollment Reminder',
    subject: 'Open Enrollment Closes Friday — Act Now',
    segmentId: 1,
    segmentName: 'Test',
    campaignName: 'Q1 Benefits Enrollment',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-23T14:30:00Z',
    deliveredAt: '2026-03-23T14:30:15Z',
    openedAt: null,
    clickedAt: null,
    status: 'Delivered',
  },
  {
    id: 'comm-004',
    contactId: 6,
    contactName: 'Abigail B. Hill',
    contactEmail: 'abigail.hill316@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-1',
    templateName: 'Q1 Benefits Enrollment Reminder',
    subject: 'Open Enrollment Closes Friday — Act Now',
    segmentId: 1,
    segmentName: 'Test',
    campaignName: 'Q1 Benefits Enrollment',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-23T14:30:00Z',
    deliveredAt: null,
    openedAt: null,
    clickedAt: null,
    status: 'Bounced',
  },
  {
    id: 'comm-005',
    contactId: 7,
    contactName: 'Abigail B. Hill',
    contactEmail: 'abigail.hill125@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-1',
    templateName: 'Q1 Benefits Enrollment Reminder',
    subject: 'Open Enrollment Closes Friday — Act Now',
    segmentId: 1,
    segmentName: 'Test',
    campaignName: 'Q1 Benefits Enrollment',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-23T14:30:00Z',
    deliveredAt: '2026-03-23T14:30:10Z',
    openedAt: '2026-03-24T08:05:00Z',
    clickedAt: '2026-03-24T08:06:15Z',
    repliedAt: '2026-03-24T09:30:00Z',
    status: 'Replied',
  },

  // ── High Balance Check-In (segment 2) ──────────────────────────────────────
  {
    id: 'comm-006',
    contactId: 1,
    contactName: 'Abigail A. Clark',
    contactEmail: 'abigail.clark213@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-10',
    templateName: 'High Balance Quarterly Check-In',
    subject: 'Your Quarterly Plan Balance Update & Optimization Tips',
    segmentId: 2,
    segmentName: 'High Balance Participants',
    campaignName: 'High Balance Q1 Check-In',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-18T10:00:00Z',
    deliveredAt: '2026-03-18T10:00:09Z',
    openedAt: '2026-03-18T12:30:00Z',
    clickedAt: '2026-03-18T12:32:00Z',
    repliedAt: '2026-03-18T14:10:00Z',
    status: 'Replied',
  },
  {
    id: 'comm-007',
    contactId: 11,
    contactName: 'Abigail C. Allen',
    contactEmail: 'abigail.allen39@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-10',
    templateName: 'High Balance Quarterly Check-In',
    subject: 'Your Quarterly Plan Balance Update & Optimization Tips',
    segmentId: 2,
    segmentName: 'High Balance Participants',
    campaignName: 'High Balance Q1 Check-In',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-18T10:00:00Z',
    deliveredAt: '2026-03-18T10:00:11Z',
    openedAt: '2026-03-19T09:15:00Z',
    clickedAt: null,
    status: 'Opened',
  },
  {
    id: 'comm-008',
    contactId: 13,
    contactName: 'Abigail C. Baker',
    contactEmail: 'abigail.baker162@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-10',
    templateName: 'High Balance Quarterly Check-In',
    subject: 'Your Quarterly Plan Balance Update & Optimization Tips',
    segmentId: 2,
    segmentName: 'High Balance Participants',
    campaignName: 'High Balance Q1 Check-In',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-18T10:00:00Z',
    deliveredAt: '2026-03-18T10:00:07Z',
    openedAt: null,
    clickedAt: null,
    status: 'Delivered',
  },
  {
    id: 'comm-009',
    contactId: 14,
    contactName: 'Abigail C. Lewis',
    contactEmail: 'abigail.lewis161@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-10',
    templateName: 'High Balance Quarterly Check-In',
    subject: 'Your Quarterly Plan Balance Update & Optimization Tips',
    segmentId: 2,
    segmentName: 'High Balance Participants',
    campaignName: 'High Balance Q1 Check-In',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-18T10:00:00Z',
    deliveredAt: '2026-03-18T10:00:14Z',
    openedAt: '2026-03-18T18:45:00Z',
    clickedAt: '2026-03-18T18:47:30Z',
    status: 'Clicked',
  },

  // ── Welcome emails for new hires (segment 3) ──────────────────────────────
  {
    id: 'comm-010',
    contactId: 19,
    contactName: 'Abigail D. Scott',
    contactEmail: 'abigail.scott242@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-8',
    templateName: 'New Hire Onboarding - Plan Intro',
    subject: 'Welcome Aboard! Let\'s Get You Started With Your Benefits',
    segmentId: 3,
    segmentName: 'New Hires 2026',
    campaignName: 'New Hire Onboarding',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-12T09:00:00Z',
    deliveredAt: '2026-03-12T09:00:06Z',
    openedAt: '2026-03-12T09:22:00Z',
    clickedAt: '2026-03-12T09:24:00Z',
    repliedAt: '2026-03-12T11:05:00Z',
    status: 'Replied',
  },

  // ── California Employees — 401(k) nudge (segment 4) ───────────────────────
  {
    id: 'comm-011',
    contactId: 0,
    contactName: 'Abigail A. Anderson',
    contactEmail: 'abigail.anderson87@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-3',
    templateName: '401(k) Contribution Increase Nudge',
    subject: 'A Small Increase Today Could Mean $50K+ More at Retirement',
    segmentId: 4,
    segmentName: 'California Employees',
    campaignName: 'CA Contribution Boost',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-10T11:00:00Z',
    deliveredAt: '2026-03-10T11:00:05Z',
    openedAt: '2026-03-10T14:20:00Z',
    clickedAt: null,
    status: 'Opened',
  },
  {
    id: 'comm-012',
    contactId: 3,
    contactName: 'Abigail A. Mitchell',
    contactEmail: 'abigail.mitchell376@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-3',
    templateName: '401(k) Contribution Increase Nudge',
    subject: 'A Small Increase Today Could Mean $50K+ More at Retirement',
    segmentId: 4,
    segmentName: 'California Employees',
    campaignName: 'CA Contribution Boost',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-10T11:00:00Z',
    deliveredAt: '2026-03-10T11:00:09Z',
    openedAt: null,
    clickedAt: null,
    status: 'Delivered',
  },

  // ── Individual one-off sends (no segment) ─────────────────────────────────
  {
    id: 'comm-013',
    contactId: 0,
    contactName: 'Abigail A. Anderson',
    contactEmail: 'abigail.anderson87@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-4',
    templateName: 'Missing Beneficiary Alert',
    subject: 'Action Required: Your Beneficiary Designation Is Incomplete',
    segmentId: null,
    segmentName: null,
    campaignName: null,
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-20T16:00:00Z',
    deliveredAt: '2026-03-20T16:00:04Z',
    openedAt: '2026-03-20T17:10:00Z',
    clickedAt: '2026-03-20T17:12:00Z',
    status: 'Clicked',
  },
  {
    id: 'comm-014',
    contactId: 2,
    contactName: 'Abigail A. Lewis',
    contactEmail: 'abigail.lewis467@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-4',
    templateName: 'Missing Beneficiary Alert',
    subject: 'Action Required: Your Beneficiary Designation Is Incomplete',
    segmentId: null,
    segmentName: null,
    campaignName: null,
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-19T10:30:00Z',
    deliveredAt: '2026-03-19T10:30:07Z',
    openedAt: null,
    clickedAt: null,
    status: 'Delivered',
  },
  {
    id: 'comm-015',
    contactId: 4,
    contactName: 'Abigail A. Nguyen',
    contactEmail: 'abigail.nguyen372@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-6',
    templateName: 'Catch-Up Contribution Eligibility',
    subject: "You're Now Eligible for Catch-Up Contributions",
    segmentId: null,
    segmentName: null,
    campaignName: null,
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-17T13:00:00Z',
    deliveredAt: '2026-03-17T13:00:11Z',
    openedAt: '2026-03-17T20:05:00Z',
    clickedAt: null,
    status: 'Opened',
  },

  // ── Trigger-based communications ──────────────────────────────────────────
  {
    id: 'comm-016',
    contactId: 8,
    contactName: 'Abigail B. Rivera',
    contactEmail: 'abigail.rivera353@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.TRIGGER_FIRED,
    templateId: 'tpl-2',
    templateName: 'Welcome to Your Plan',
    subject: "Welcome! Here's Everything You Need to Know About Your Retirement Plan",
    segmentId: null,
    segmentName: null,
    campaignName: 'Auto-Welcome Trigger',
    sentBy: 'System',
    sentAt: '2026-03-22T08:00:00Z',
    deliveredAt: '2026-03-22T08:00:05Z',
    openedAt: '2026-03-22T08:35:00Z',
    clickedAt: '2026-03-22T08:37:00Z',
    repliedAt: '2026-03-22T10:20:00Z',
    status: 'Replied',
  },
  {
    id: 'comm-017',
    contactId: 9,
    contactName: 'Abigail B. Thompson',
    contactEmail: 'abigail.thompson253@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.TRIGGER_FIRED,
    templateId: 'tpl-9',
    templateName: 'Inactive Participant Re-engagement',
    subject: "We Haven't Heard From You — Your Plan Balance Is Waiting",
    segmentId: null,
    segmentName: null,
    campaignName: 'Inactivity Trigger',
    sentBy: 'System',
    sentAt: '2026-03-21T07:00:00Z',
    deliveredAt: '2026-03-21T07:00:08Z',
    openedAt: null,
    clickedAt: null,
    status: 'Delivered',
  },
  {
    id: 'comm-018',
    contactId: 10,
    contactName: 'Abigail B. Thompson',
    contactEmail: 'abigail.thompson301@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.TRIGGER_FIRED,
    templateId: 'tpl-9',
    templateName: 'Inactive Participant Re-engagement',
    subject: "We Haven't Heard From You — Your Plan Balance Is Waiting",
    segmentId: null,
    segmentName: null,
    campaignName: 'Inactivity Trigger',
    sentBy: 'System',
    sentAt: '2026-03-21T07:00:00Z',
    deliveredAt: '2026-03-21T07:00:12Z',
    openedAt: '2026-03-22T11:00:00Z',
    clickedAt: null,
    status: 'Opened',
  },

  // ── Annual Plan Performance blast (company-wide, no segment) ──────────────
  {
    id: 'comm-019',
    contactId: 0,
    contactName: 'Abigail A. Anderson',
    contactEmail: 'abigail.anderson87@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-5',
    templateName: 'Annual Plan Performance Summary',
    subject: 'Your 2025 Retirement Plan Year in Review',
    segmentId: null,
    segmentName: null,
    campaignName: 'Annual Review 2025',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-01-15T09:00:00Z',
    deliveredAt: '2026-01-15T09:00:06Z',
    openedAt: '2026-01-15T10:20:00Z',
    clickedAt: '2026-01-15T10:22:00Z',
    status: 'Clicked',
  },
  {
    id: 'comm-020',
    contactId: 1,
    contactName: 'Abigail A. Clark',
    contactEmail: 'abigail.clark213@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-5',
    templateName: 'Annual Plan Performance Summary',
    subject: 'Your 2025 Retirement Plan Year in Review',
    segmentId: null,
    segmentName: null,
    campaignName: 'Annual Review 2025',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-01-15T09:00:00Z',
    deliveredAt: '2026-01-15T09:00:10Z',
    openedAt: '2026-01-15T14:45:00Z',
    clickedAt: null,
    status: 'Opened',
  },
  {
    id: 'comm-021',
    contactId: 2,
    contactName: 'Abigail A. Lewis',
    contactEmail: 'abigail.lewis467@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-5',
    templateName: 'Annual Plan Performance Summary',
    subject: 'Your 2025 Retirement Plan Year in Review',
    segmentId: null,
    segmentName: null,
    campaignName: 'Annual Review 2025',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-01-15T09:00:00Z',
    deliveredAt: '2026-01-15T09:00:13Z',
    openedAt: null,
    clickedAt: null,
    status: 'Delivered',
  },
  {
    id: 'comm-022',
    contactId: 3,
    contactName: 'Abigail A. Mitchell',
    contactEmail: 'abigail.mitchell376@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-5',
    templateName: 'Annual Plan Performance Summary',
    subject: 'Your 2025 Retirement Plan Year in Review',
    segmentId: null,
    segmentName: null,
    campaignName: 'Annual Review 2025',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-01-15T09:00:00Z',
    deliveredAt: null,
    openedAt: null,
    clickedAt: null,
    status: 'Bounced',
  },
  {
    id: 'comm-023',
    contactId: 4,
    contactName: 'Abigail A. Nguyen',
    contactEmail: 'abigail.nguyen372@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-5',
    templateName: 'Annual Plan Performance Summary',
    subject: 'Your 2025 Retirement Plan Year in Review',
    segmentId: null,
    segmentName: null,
    campaignName: 'Annual Review 2025',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-01-15T09:00:00Z',
    deliveredAt: '2026-01-15T09:00:08Z',
    openedAt: '2026-01-16T08:00:00Z',
    clickedAt: '2026-01-16T08:02:00Z',
    status: 'Clicked',
  },
  {
    id: 'comm-024',
    contactId: 5,
    contactName: 'Abigail A. Thompson',
    contactEmail: 'abigail.thompson234@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-5',
    templateName: 'Annual Plan Performance Summary',
    subject: 'Your 2025 Retirement Plan Year in Review',
    segmentId: null,
    segmentName: null,
    campaignName: 'Annual Review 2025',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-01-15T09:00:00Z',
    deliveredAt: '2026-01-15T09:00:05Z',
    openedAt: '2026-01-15T11:30:00Z',
    clickedAt: null,
    status: 'Opened',
  },

  // ── Payroll integration confirmations ─────────────────────────────────────
  {
    id: 'comm-025',
    contactId: 15,
    contactName: 'Abigail D. Baker',
    contactEmail: 'abigail.baker46@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-7',
    templateName: 'Payroll Integration Confirmation',
    subject: 'Your Payroll Data Has Been Successfully Linked',
    segmentId: null,
    segmentName: null,
    campaignName: null,
    sentBy: 'System',
    sentAt: '2026-03-15T12:00:00Z',
    deliveredAt: '2026-03-15T12:00:04Z',
    openedAt: '2026-03-15T12:10:00Z',
    clickedAt: null,
    status: 'Opened',
  },
  {
    id: 'comm-026',
    contactId: 16,
    contactName: 'Abigail D. Clark',
    contactEmail: 'abigail.clark34@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-7',
    templateName: 'Payroll Integration Confirmation',
    subject: 'Your Payroll Data Has Been Successfully Linked',
    segmentId: null,
    segmentName: null,
    campaignName: null,
    sentBy: 'System',
    sentAt: '2026-03-15T12:00:00Z',
    deliveredAt: '2026-03-15T12:00:09Z',
    openedAt: '2026-03-15T14:30:00Z',
    clickedAt: '2026-03-15T14:31:00Z',
    status: 'Clicked',
  },

  // ── Unsubscribe events ────────────────────────────────────────────────────
  {
    id: 'comm-027',
    contactId: 12,
    contactName: 'Abigail C. Anderson',
    contactEmail: 'abigail.anderson393@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_UNSUBSCRIBED,
    templateId: 'tpl-3',
    templateName: '401(k) Contribution Increase Nudge',
    subject: 'A Small Increase Today Could Mean $50K+ More at Retirement',
    segmentId: 4,
    segmentName: 'California Employees',
    campaignName: 'CA Contribution Boost',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-10T11:00:00Z',
    deliveredAt: '2026-03-10T11:00:06Z',
    openedAt: '2026-03-10T13:00:00Z',
    clickedAt: null,
    status: 'Unsubscribed',
  },

  // ── Campaign enrollment events ────────────────────────────────────────────
  {
    id: 'comm-028',
    contactId: 6,
    contactName: 'Abigail B. Hill',
    contactEmail: 'abigail.hill316@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.CAMPAIGN_ENROLLED,
    templateId: null,
    templateName: null,
    subject: null,
    segmentId: 1,
    segmentName: 'Test',
    campaignName: 'Q1 Benefits Enrollment',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-23T14:29:00Z',
    deliveredAt: null,
    openedAt: null,
    clickedAt: null,
    status: 'Enrolled',
  },
  {
    id: 'comm-029',
    contactId: 7,
    contactName: 'Abigail B. Hill',
    contactEmail: 'abigail.hill125@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.CAMPAIGN_ENROLLED,
    templateId: null,
    templateName: null,
    subject: null,
    segmentId: 2,
    segmentName: 'High Balance Participants',
    campaignName: 'High Balance Q1 Check-In',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-18T09:59:00Z',
    deliveredAt: null,
    openedAt: null,
    clickedAt: null,
    status: 'Enrolled',
  },

  // ── More recent sends to spread across contacts ───────────────────────────
  {
    id: 'comm-030',
    contactId: 20,
    contactName: 'Abigail E. Allen',
    contactEmail: 'abigail.allen488@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-3',
    templateName: '401(k) Contribution Increase Nudge',
    subject: 'A Small Increase Today Could Mean $50K+ More at Retirement',
    segmentId: 1,
    segmentName: 'Test',
    campaignName: 'Q1 Contribution Boost',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-24T10:00:00Z',
    deliveredAt: '2026-03-24T10:00:07Z',
    openedAt: '2026-03-24T11:15:00Z',
    clickedAt: null,
    status: 'Opened',
  },
  {
    id: 'comm-031',
    contactId: 21,
    contactName: 'Abigail E. Mitchell',
    contactEmail: 'abigail.mitchell69@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-3',
    templateName: '401(k) Contribution Increase Nudge',
    subject: 'A Small Increase Today Could Mean $50K+ More at Retirement',
    segmentId: 1,
    segmentName: 'Test',
    campaignName: 'Q1 Contribution Boost',
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-24T10:00:00Z',
    deliveredAt: '2026-03-24T10:00:11Z',
    openedAt: '2026-03-24T16:00:00Z',
    clickedAt: '2026-03-24T16:02:00Z',
    repliedAt: '2026-03-24T17:45:00Z',
    status: 'Replied',
  },
  {
    id: 'comm-032',
    contactId: 22,
    contactName: 'Abigail E. Thompson',
    contactEmail: 'abigail.thompson301@viserly.demo',
    account: 'Demo Company ABC',
    type: COMM_TYPES.EMAIL_SENT,
    templateId: 'tpl-6',
    templateName: 'Catch-Up Contribution Eligibility',
    subject: "You're Now Eligible for Catch-Up Contributions",
    segmentId: null,
    segmentName: null,
    campaignName: null,
    sentBy: 'Cameron Abernethy',
    sentAt: '2026-03-22T15:00:00Z',
    deliveredAt: '2026-03-22T15:00:06Z',
    openedAt: null,
    clickedAt: null,
    status: 'Delivered',
  },
]

// ─── Helper functions for filtering / aggregating ──────────────────────────────

/** Get all comms for a specific contact (by contactId) */
export function getCommsForContact(contactId) {
  return COMMUNICATION_HISTORY.filter((c) => c.contactId === contactId)
    .sort((a, b) => new Date(b.sentAt) - new Date(a.sentAt))
}

/** Get all comms for a specific segment (by segmentId) */
export function getCommsForSegment(segmentId) {
  return COMMUNICATION_HISTORY.filter((c) => c.segmentId === segmentId)
    .sort((a, b) => new Date(b.sentAt) - new Date(a.sentAt))
}

/** Get all comms for a specific campaign name */
export function getCommsForCampaign(campaignName) {
  return COMMUNICATION_HISTORY.filter((c) => c.campaignName === campaignName)
    .sort((a, b) => new Date(b.sentAt) - new Date(a.sentAt))
}

/** Get all comms for a specific account / company */
export function getCommsForAccount(accountName) {
  return COMMUNICATION_HISTORY.filter((c) => c.account === accountName)
    .sort((a, b) => new Date(b.sentAt) - new Date(a.sentAt))
}

/** Aggregate stats across a set of comm records */
export function getCommStats(records) {
  const total = records.length
  const sent = records.filter((r) => r.type === COMM_TYPES.EMAIL_SENT || r.type === COMM_TYPES.TRIGGER_FIRED).length
  const delivered = records.filter((r) => r.deliveredAt).length
  const opened = records.filter((r) => r.openedAt).length
  const clicked = records.filter((r) => r.clickedAt).length
  const replied = records.filter((r) => r.repliedAt).length
  const bounced = records.filter((r) => r.status === 'Bounced').length
  const unsubscribed = records.filter((r) => r.status === 'Unsubscribed').length

  return {
    total,
    sent,
    delivered,
    opened,
    clicked,
    replied,
    bounced,
    unsubscribed,
    openRate: delivered > 0 ? ((opened / delivered) * 100).toFixed(1) : '0.0',
    clickRate: opened > 0 ? ((clicked / opened) * 100).toFixed(1) : '0.0',
    replyRate: sent > 0 ? ((replied / sent) * 100).toFixed(1) : '0.0',
    deliveryRate: sent > 0 ? ((delivered / sent) * 100).toFixed(1) : '0.0',
  }
}

/** Get unique campaign names */
export function getUniqueCampaigns() {
  const campaigns = new Map()
  COMMUNICATION_HISTORY.forEach((c) => {
    if (c.campaignName && !campaigns.has(c.campaignName)) {
      const records = getCommsForCampaign(c.campaignName)
      campaigns.set(c.campaignName, {
        name: c.campaignName,
        segmentName: c.segmentName,
        templateName: c.templateName,
        sentBy: c.sentBy,
        sentAt: c.sentAt,
        recordCount: records.length,
        stats: getCommStats(records),
      })
    }
  })
  return Array.from(campaigns.values()).sort((a, b) => new Date(b.sentAt) - new Date(a.sentAt))
}
