const payrollProviders = [
  '360 Simplicity',
  'Abacus Payroll Services',
  'Abacus Paysystems',
  'ABS Payroll',
  'Absolute Wages',
  'AccuPay Systems',
  'Accurate Pay Systems',
  'Accurate Payroll NY',
  'Adams Brown Payroll Services',
  'Adirondack Payroll Services',
  'ADP Run',
  'ADP Workforce Now',
  'ADP Workforce Now Nextgen',
  'All Business Payroll',
  'Allied Payroll Services',
  'AmCheck Technology',
  'Apollo Payroll',
  'Applied Payroll Solutions',
  'ASAP Accounting & Payroll',
  'AspenHR',
  'AssetHR',
  'B2E Solutions',
  'Back Office Support Solutions',
  'Balance Point HCM',
  'Baron Payroll',
  'Bayview Payroll Services',
  'BBS Financial, LLC',
  'Birch Tree Business Solutions',
  'Blue Sky Payroll',
  'Boutique Payroll Company',
  'Capital Payroll Partners',
  'CAVU HCM',
  'Ceridian',
  'Charlotte Payroll',
  'Checkmate HCM',
  'CheckRight NW',
  'Clarity HCM',
  'ClearPalm Inc',
  'CNY Payroll Services, Inc.',
  'Coastal Payroll',
  'Commonwealth Payroll',
  'Company Payroll Processing',
  'CompassOne Payroll',
  'Complete Payroll Resources',
  'CongruityHR',
  'Contempo HCM',
  'Corneliuson & Associates',
  'CS3 Technology',
  'CTR Payroll & HR',
  'Direct East',
  'Dominion Payroll',
  'Dominion Payroll - Colorado',
  'Employ Drive',
  'Employee Payment Solutions',
  'Entrust Payroll Solutions',
  'EWH Small Business Accounting',
  'Express Data Systems',
  'EZ Payroll',
  'FocusPay Solutions',
  'Gem Payroll',
  'Genesis PPG',
  'Guardian Payroll',
  'HigherUp HCM',
  'HireLevel HCM',
  'Hometown Payroll Solutions',
  'Horizon Payroll',
  'HRmonious',
  'HRtoGO',
  'Human Elements',
  'Hunter Payroll Systems',
  'inFocus Payroll',
  'Inova Payroll',
  'iPay Solutions',
  'isolved',
  'Kabel Business Services',
  'Keystone Payroll',
  'Landmark Payroll',
  'Ledger Payroll',
  'Ludt Payroll',
  'Market Dimensions Inc',
  'Metro Payroll - Apex',
  'Metro Payroll - UKG',
  'Miami Payroll Center',
  'Miter',
  'New England Payroll Services',
  'On-Time Payroll',
  'Onyx HR',
  'Optima Benefits and Payroll',
  'Pacific Payroll Group',
  'Paper Trails Payroll',
  'Paragon HCM',
  'Paycom',
  'Payday Employer Solutions',
  'PayDay Masters',
  'Payficiency',
  'Payfluence HCM',
  'PayFWDs',
  'Paylocity',
  'Paymedia',
  'PayNW',
  'PayPlus',
  'PayPlus LLC',
  'PayPro HCS',
  'Payroll Company Inc',
  'Payroll Data Processing',
  'Payroll Hub',
  'Payroll Processors',
  'Payroll Vault',
  'Payrolls Plus',
  'PaySource Inc',
  'Paywerx',
  'Performance Pay',
  'Pinkerton Payroll & Insurance',
  'Pioneer Payroll Solutions',
  'PPA',
  'Press Gold Group',
  'Quartermaster Payroll Providers',
  'QuickBooks Online',
  'Rabco Payroll',
  'Ridgecrest Solutions',
  'River Run Payroll',
  'RKL LLP',
  'Savant HCM',
  'SmartBean Payroll',
  'SourceOne Payroll',
  'Spruce Valley',
  'Tax & Payroll Shelter',
  'The Payroll Company',
  'Thread HCM',
  'Three Pillars Bookkeeping',
  'Time & Payroll',
  'Tolu Payroll',
  'TP Payroll',
  'UKG Ready',
  'Vertilocity',
  'Vision Payroll',
  'Wipfli',
  'WorkGroup Payroll',
  'Workplace HCM - Apex',
  'Workplace HCM - iSolved',
  'World Payroll & HR',
  'WORX Payroll',
  'Your Payroll Department',
  'YPD HCM',
]

export default payrollProviders
